### ISSUE TITLE
why use require<any>not import to include style?

### ISSUE THREAD

**Issue by linhuiw** [everdimension/react-component-ts-boilerplate#1]
I don't know why you choose require<any> instead of import?

```javascript
require<any>('./styles.css');
```
not import
```javascript
import ('./style/css');
```

**Comment by everdimension** [comment]
I was under the impression that it wouldn't work like that without special declarations for this file type.

I tried it and it seems ok.

**Comment by linhuiw** [comment]
OK, TKS.
